apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: e-commerce-pod
  namespace: vasist-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - name: ecommerce
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hospital-pod
  namespace: vasist-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospital
  template:
    metadata:
      labels:
        app: hospital
    spec:
      containers:
        - name: hospital
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: school-pod
  namespace: vasist-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: school
  template:
    metadata:
      labels:
        app: school
    spec:
      containers:
        - name: school
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: vegitable-pod
  namespace: vasist-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vegitable
  template:
    metadata:
      labels:
        app: vegitable
    spec:
      containers:
        - name: vegitable
          image: nginx:latest
          ports:
            - containerPort: 80